name: Parse and Combine JSON Files

on:
    push:
        branches: [ main ]

jobs:
  parse_and_combine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}


    - name: Parsing and Combining JSON Files
      run: |
        git config --global user.email "a@tushynski.me"
        git config --global user.name "Alex"
        json_files=()
        while IFS= read -r -d '' file; do
          json_files+=("$(cat "$file")")
        done < <(find vectors -type f -name "*.json" -print0)
        echo "[$(IFS=,; echo "${json_files[*]}")]" > combined.json
        git add combined.json
        git commit -m "Update combined.json"
        git push origin main

          
